# Routes Advert
oc_platform_home:
    path:      /{page}
    defaults:
        { _controller: OCPlatform2Bundle:Advert:index }
        page:   1
    requirements:
        page:  \d*

oc_platform_view:
    path:      /advert/{id}
    defaults:
        { _controller: OCPlatform2Bundle:Advert:view }
    requirements:
        id: \d+

oc_platform_add:
    path:      /add
    defaults:
        { _controller: OCPlatform2Bundle:Advert:add }

oc_platform_edit:
    path:      /edit/{id}
    defaults:
        { _controller: OCPlatform2Bundle:Advert:edit }
    requirements:
        id: \d+

oc_platform_delete:
    path:      /delete/{id}
    defaults:
        { _controller: OCPlatform2Bundle:Advert:delete }
    requirements:
        id: \d+

# exemples :

#oc_platform_view_slug:
#    path:      /{year}/{slug}.{format}
#    defaults:
#        _controller: OCPlatform2Bundle:Advert:viewSlug
##        valeur prise par défaut rendant le paramètre facultatif
#        format:   html
##        contraintes
#    requirements:
#        year:   \d{4}
#        format: html|xml