# Routes Advert
oc_platform_home:
    path:      /{page}
    defaults:
        _controller: OCPlatform2Bundle:Advert:index
        page:        1
    requirements:
        page: \d*

oc_platform_view:
    path:      /advert/{id}
    defaults:
        _controller: OCPlatform2Bundle:Advert:view
    requirements:
        id: \d+

oc_platform_add:
    path:      /add
    defaults:
        _controller: OCPlatform2Bundle:Advert:add

oc_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: OCPlatform2Bundle:Advert:edit
    requirements:
        id: \d+

oc_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: OCPlatform2Bundle:Advert:delete
    requirements:
        id: \d+

oc_platform_menu:
    path:      /menu
    defaults:
        _controller: OCPlatform2Bundle:Advert:menu

oc_platform_edit_image:
    path:      /edit-image/{advertId}
    defaults:
        _controller: OCPlatform2Bundle:Advert:editImage
    requirements:
        advertId: \d+
